apiVersion: v1
kind: Service
metadata:
  labels:
    app: emqx
  name: mqtt-svc
  namespace: python-app
spec:
  ports:
  - name: 1883-1883
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: emqx
  type: ClusterIP
