apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-app
  name: python-app
  namespace: python-app
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
    nodePort: 30001
  selector:
    app: python-app
  type: NodePort
