apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app
  name: python-app
  namespace: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - image: "123.60.182.14/python-app/python-app:v1"
        name: python-app
        env: 
        - name: MQTT_HOST
          value: "mqtt-svc"
